name: Build and Package
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [20.x]  # 支持的 Node.js 版本
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Build project for each directory
      run: |
        cd car-show && npm instal && npm run build  # 替换为适合你项目的命令
